apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler

metadata:
  name: recovvo-api

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recovvo-api

  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
