apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: recovvo-api
namespace: recovvo-api
resources:
  - service.yaml
  - namespace.yaml
  - deployment.yaml
  - hpa.yaml
